### ISSUE TITLE
もしかして：random.choice

### ISSUE THREAD

**Issue by c0b21047** [SugaharaRintaro/ProjExD#10]
https://github.com/SugaharaRintaro/ProjExD/blob/550680331981e6db032cc71051da0eb40c2febd3/ex04/dodge_bomb.py#L2
randomモジュールはrandintのみインポートしているためコード内で使っているchoiceはrandomモジュールのchoiceじゃない

**Comment by SugaharaRintaro** [comment]
ありがとうございます．
動いてたので無視してましたが挙動が分からなかったのでramdomモジュールのものに直しました．
