### ISSUE TITLE
爆弾を一斉に作るのはすごいですね

### ISSUE THREAD

**Issue by c0b21073** [SugaharaRintaro/ProjExD#11]
https://github.com/SugaharaRintaro/ProjExD/blob/ea7e21231e15ba2fe9ef67b4dd4a89d2576e9c4a/ex04/dodge_bomb.py#L15

**Comment by SugaharaRintaro** [comment]
ありがとうございます
まとめてリストに入れると移動処理や接触判定もfor文で行えるので楽です
