### ISSUE TITLE
俺にはなかった発想

### ISSUE THREAD

**Issue by c0b21149** [SugaharaRintaro/ProjExD#2]
https://github.com/SugaharaRintaro/ProjExD/blob/43c05dc4dd1222b948f83698c0ca9717c83d1c2f/ex01/alphabet.py#L12

ランダムに数字を生成してからそれをアルファベットに直す方がスマートだと思った

**Comment by SugaharaRintaro** [comment]
ありがとう
ただ重複した数字ができないように気をつける必要がありました．
