### ISSUE TITLE
if文

### ISSUE THREAD

**Issue by c0b21149** [SugaharaRintaro/ProjExD#7]
この場合はelif ではなくifでもいいのでは？
どっちが奇麗なのかはわかりかねるが打つ文字数が少なくはなる
https://github.com/SugaharaRintaro/ProjExD/blob/de4bda80572814f75fc1aaa1e0ec7bd1a680b6bf/ex03/maze.py#L22

**Comment by SugaharaRintaro** [comment]
コメントありがとうございます
ifだと例えばUpが入力されてるときに下の3つも比較してしまうので計算量が増えてしまいます．
見た目と手間はifのほうがいいので好みですが
